using System;


namespace DatabaseApp_Paul_Zaldea
{
    public enum Currencies
    {
        EUR = 0,
        RUB = 1,
        USD = 2,
        AUD = 3,
        CHF = 4,
        ARS = 5,
        UAH = 6,
        ZAR = 7,
        HKD = 8,
        MOP = 9,
        PHP = 10,
        MYR = 11,
        SGD = 12,
        NAD = 13,
        BWP = 14,
        MAD = 15,
        MUR = 16,
        MWK = 17,
        ZWD = 18,
        KES = 19,
        SCR = 20,
        AOA = 21,
        TZS = 22,
        GHS = 23,
        ZMK = 24,
        MGA = 25,
        HUF = 26,
        LVL = 27,
        EEK = 28,
        LTL = 29,
        BOB = 30,
        BRL = 31,
        CLP = 32,
        COP = 33,
        GYD = 34,
        PYG = 35,
        PEN = 36,
        SRD = 37,
        UYU = 38,
        VEB = 39,
        ROL = 40,
        RON = 41,
        KZT = 42,
        LSL = 43,
        THB = 44,
        GBP = 45,
        PLN = 46,
        DKK = 47,
        SEK = 48,
        CZK = 49,
        HRK = 50,
        BGN = 51,
        RSD = 52,
        TRY = 53,
        DOP = 54,
        AWG = 55,
        NOK = 56,
        CAD = 57,
        JPY = 58,
        INR = 59,
        RWF = 60,
        ALL = 61,
        MXN = 62,
        ISK = 63,
        NZD = 64,
        KRW = 65,
        TWD = 66,
        ILS = 67,
        ZMW = 68,
        PAB = 69,
        CRC = 70,
        ANG = 71,
        MKD = 72,
        VND = 73,
        LKR = 74,
        GEL = 75,
        GIP = 76,
        NGN = 77,
        AED = 78,
        SAR = 79,
        BBD = 80,
        TTD = 81,
        QAR = 82,
        GTQ = 83,
        HNL = 84,
        IDR = 85,
        SZL = 86,
        MZN = 87,
        EGP = 88,
        NIO = 89,
        BSD = 90,
        BMD = 91,
        XCD = 92,
        JMD = 93,
        BZD = 94,
        VEF = 95,
        UGX = 96,
        CNY = 97,
        XPF = 98,
        XOF = 99,
        XAF = 100,
        ECO = 101,
        IXP = 102,
        CIP = 103,
        GXP = 104,
        VUV = 105,
        LAK = 106
    }

    public class CurrencyConverter
    {
        public static Currencies ConvertToCurrency(string currencyCode)
        {
            if (Enum.TryParse<Currencies>(currencyCode, out Currencies currency))
            {
                return currency;
            }

            return Currencies.EUR;
        }
    }
}
